#!/usr/bin/env node
const { execSync } = require("child_process");
const fs = require("fs");

let html = `<html>

<head>
    <title>Digest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-weight: 400;
            font-family:
                system-ui,
                -apple-system,
                BlinkMacSystemFont,
                "Segoe UI",
                Roboto,
                Oxygen,
                Ubuntu,
                Cantarell,
                "Open Sans",
                "Helvetica Neue",
                sans-serif;
            font-size: 16px;
        }

        body {
            font-size: 1rem;
            padding: 1rem;
        }

        p {
            margin-bottom: 0.5rem;
        }

        h1 {
            margin-bottom: 2rem;
            font-weight: bold;
        }

        h2,
        h3,
        h4,
        h5,
        h6 {
            margin-top: 2rem;
            margin-bottom: 0.5rem;
        }



        pre#app {
            display: none;
        }

        #links { display: flex; gap: 0.5rem; align-content: center; margin-bottom: 1rem; }

        hr { height: 1px; background: #ccc; margin: 1rem 0; border: 0 !important; }

        #render p { margin-top: 0.75rem; }

    </style>
</head>

<body>
    <div id="links">
        <a href="./upcoming.html">Upcoming</a>
        <a href="./">Latest</a>
        <a href="./previous.html">Previous</a>
    </div>
    <pre id="app">{{content}}</pre>
    <div id="render"></div>
    <script src="https://cdn.jsdelivr.net/npm/marked/lib/marked.umd.js"></script>
    <script>
        let pre = document.getElementById('app')
        let render = document.getElementById('render')
        let md = pre.innerText?.split("\\n").filter(t => t !== "\\n").map(t => t.trim()).join("\\n\\n");
        render.innerHTML = marked.parse(md);
        let links = Array.from(document.querySelectorAll('#render a'));
        document.querySelector('h1').innerText = document.querySelector('h1').innerText + ' — ' + links.length + ' links.'
    </script>
</body>

</html>`;

const main = async () => {
  [0, 1, 2].forEach(async (num) => await update(num));
  console.log("Done!");
};

const update = async (num) => {
  let name = ["upcoming", "index", "previous"];
  let c = execSync(`${process.env.RDIGEST_PATH} digest ${num + 1}`, {
    encoding: "utf-8"
  });
  c = html.replace("{{content}}", c);
  fs.writeFileSync(`./${name[num]}.html`, c);
};

main();
